version: '3.9'
services:
 web:
  build: ./react_frontend
  container_name: react1
  ports:
   - "3000:3000"
  volumes:
   - ./react_frontend:/react-app
  stdin_open: true
  tty: true
 app:
  image: node:latest
  container_name: nodeapp
  environment:
   DB_HOST: mysql1
   DB_PORT: 3306
   DB_USER: root
   DB_PASSWORD: admin
  ports:
   - "8080:8080"
  command: ["bin/bash"]
  volumes:
   - ./Backend:/code
  depends_on:
    mysql1: 
      condition: service_healthy
  stdin_open: true
  tty: true
 mysql1:
  image: mysql:5.7
  restart: always
  container_name: db1
  environment:
   - MYSQL_ROOT_PASSWORD=admin
  healthcheck:
   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-padmin"]
   timeout: 20s # Timeout for each health checking.
   retries: 10 # Hou many times retries.
  ports:
   - '3306:3306'
  volumes:
   - ./db:/var/lib/mysql
  stdin_open: true
  tty: true
volumes: 
  db:
     driver: local